CREATE TABLE run_records (
    id              VARCHAR(36) PRIMARY KEY,
    user_id         BIGINT NOT NULL,
    date            DATE NOT NULL,
    started_at      BIGINT NOT NULL,
    duration_min    INTEGER NOT NULL,
    card_id         VARCHAR(36) NOT NULL,
    card_title      VARCHAR(100) NOT NULL,
    card_tier       ENUM('S','M','L') NOT NULL,
    output_text     TEXT NOT NULL,
    output_link     VARCHAR(500),
    screenshot_note TEXT,
    file_path       VARCHAR(500),
    result          ENUM('win','lose') NOT NULL,
    game_mode       ENUM('mixed','single') NOT NULL,
    direction       VARCHAR(20),
    star_delta      INTEGER NOT NULL DEFAULT 0,
    rank_name       VARCHAR(10) NOT NULL,
    stars           INTEGER NOT NULL DEFAULT 0,
    peak_delta      INT,
    peak_score      INT,
    is_life_mode    BOOLEAN NOT NULL DEFAULT FALSE,
    used_shield     BOOLEAN NOT NULL DEFAULT FALSE,
    created_at      DATETIME DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_user_date (user_id, date),
    INDEX idx_user_mode (user_id, game_mode),
    FOREIGN KEY (user_id) REFERENCES users(id)
);
